export class Homepage {
    constructor(
        public title: string,
        public subtitle: string,
        public forTime: string,
        public subheaderLoc: string,
        public subheaderDate: string,
        public videoTitle: string,
        public videoSubtitle: string,
        public videoHidden: boolean,
        public postsTitle: string,
        public postsSubtitle: string,
        public postsButtonText: string,
        public postsButtonURL: string,
        public postOption1: string,
        public postOption2: string,
        public postOption3: string,
        public postsHidden: boolean,
        public onDemandTitle: string,
        public onDemandText: string,
        public onDemandButtonText: string,
        public onDemandButtonURL: string,
        public onDemandHidden: boolean,
        public byTheNumbersTitle: string,
        public byTheNumbersOneNumber: string,
        public byTheNumbersOneSubtitle: string,
        public byTheNumbersTwoNumber: string,
        public byTheNumbersTwoSubtitle: string,
        public byTheNumbersThreeNumber: string,
        public byTheNumbersThreeSubtitle: string,
        public byTheNumbersHidden: boolean,
        public sponsorTitle: string,
        public sponsorOneImg: string,
        public sponsorOneURL: string,
        public sponsorTwoImg: string,
        public sponsorTwoURL: string,
        public sponsorThreeImg: string,
        public sponsorThreeURL: string,
        public sponsorFourImg: string,
        public sponsorFourURL: string,
        public sponsorHidden: boolean,
        public hasCalendar: boolean,
        public calendarTitle: string,
        public calendarSectionTitle: string,
        public bannerButtonText: string,
        public bannerButtonURL: string,
        public hasBannerButton: boolean,
        public bannerButtonIsExtUrl: boolean,
        public cardOption1: string,
        public cardOption2: string,
        public cardOption3: string,
        public cardsTitle: string,
        public cardsSubtitle: string,
        public cardsHidden: boolean,
        public id: string,
    ) {
    }
}
